# Generated by Django 5.2.5 on 2025-08-10 20:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_remove_customuser_role_alter_customuser_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
