# Generated by Django 5.2.5 on 2025-08-11 18:25

import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
import inventario.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Código de barras')),
                ('qr_code', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código QR')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('sku_proveedor', models.CharField(max_length=64, unique=True, verbose_name='SKU proveedor')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo_producto', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Repuesto', 'Repuesto'), ('Servicio', 'Servicio'), ('Kit', 'Kit')], max_length=20, verbose_name='Tipo de producto')),
                ('descripcion_corta', models.TextField(verbose_name='Descripción corta')),
                ('palabras_clave', models.TextField(blank=True, null=True, verbose_name='Palabras clave')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Vendido', 'Vendido'), ('Dañado', 'Dañado'), ('Desechado', 'Desechado')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('ubicacion_principal', models.CharField(max_length=100, verbose_name='Ubicación principal')),
                ('cantidad_inicial', models.IntegerField(default=0, verbose_name='Cantidad inicial')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock actual')),
                ('unidad_medida', models.CharField(choices=[('pza', 'Pieza'), ('set', 'Set'), ('kg', 'Kg'), ('unidad_hora', 'Unidad/Hora')], max_length=20, verbose_name='Unidad de medida')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo unitario')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de alta')),
                ('marca_fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca fabricante')),
                ('modelo_fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo fabricante')),
                ('compatible_con_modelos', models.TextField(blank=True, null=True, verbose_name='Compatible con modelos')),
                ('manual_tecnico_pdf', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='manuales/', verbose_name='Manual técnico (PDF)')),
                ('precio_publico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio público')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio oferta')),
                ('oferta_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Oferta inicio')),
                ('oferta_fin', models.DateTimeField(blank=True, null=True, verbose_name='Oferta fin')),
                ('visibilidad_online', models.CharField(choices=[('Oculto', 'Oculto'), ('Catálogo', 'Catálogo'), ('Venta', 'Venta')], default='Oculto', max_length=20, verbose_name='Visibilidad online')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('largo_mm', models.IntegerField(blank=True, null=True, verbose_name='Largo (mm)')),
                ('ancho_mm', models.IntegerField(blank=True, null=True, verbose_name='Ancho (mm)')),
                ('alto_mm', models.IntegerField(blank=True, null=True, verbose_name='Alto (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor principal')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste')], max_length=3)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad (signed)')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=inventario.models.imagen_upload_to)),
                ('secuencia', models.PositiveSmallIntegerField(default=1, verbose_name='Secuencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'unique_together': {('producto', 'secuencia')},
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='inventario__sku_814480_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku_proveedor'], name='inventario__sku_pro_5ecfee_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['barcode'], name='inventario__barcode_73eb14_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['qr_code'], name='inventario__qr_code_8bd5ca_idx'),
        ),
    ]
