# Generated by Django 5.2.5 on 2025-08-12 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__barcode_73eb14_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__qr_code_8bd5ca_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_identificador',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Código identificador (QR o barra)'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_identificador'], name='inventario__codigo__4810ac_idx'),
        ),
    ]
