# Generated by Django 5.2.5 on 2025-08-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico')], default='tecnico', help_text='Rol (CharField) de acceso en XPYME', max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del rol')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos adicionales')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_obj',
            field=models.ForeignKey(blank=True, help_text='Rol vinculado al modelo Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.role', verbose_name='Rol (objeto)'),
        ),
    ]
