# Generated by Django 5.2.5 on 2025-08-09 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_role_role_customuser_role_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo base'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de creación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre contacto emergencia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono contacto emergencia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='maternal_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nss',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NSS'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paternal_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
