# Generated by Django 5.2.5 on 2025-08-10 19:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser_base_salary_customuser_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha y hora de creación'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono de emergencia debe tener 10 dígitos.')], verbose_name='Teléfono contacto emergencia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nss',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El NSS debe tener 11 dígitos.')], verbose_name='NSS'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener 10 dígitos.')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-zÑ&]{4}\\d{6}[A-Za-z0-9]{3}$', 'Formato de RFC inválido.')], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_obj',
            field=models.ForeignKey(blank=True, help_text='Rol vinculado al modelo Role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.role', verbose_name='Rol'),
        ),
    ]
